modLoader="javafml"
loaderVersion="[47,)"
license="MIT License"

[[mods]]
modId="fuzzy"
version="2.6.1"
displayName="Fuzzy"
displayURL="https://mcreator.net"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="LucaBarbaLata, David"
description="A cute mod that adds so much cute stuff!!!"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.fuzzy]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"



